# Generated by Django 2.0.1 on 2018-01-12 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0002_training_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(default=datetime.datetime.now)),
                ('hours', models.IntegerField(default=8)),
                ('account', models.CharField(max_length=50)),
            ],
        ),
    ]
