# Generated by Django 2.0.1 on 2018-01-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hours',
            options={'verbose_name_plural': 'Hours'},
        ),
        migrations.AddField(
            model_name='hours',
            name='hours',
            field=models.IntegerField(default=8),
        ),
    ]
