# Generated by Django 2.0.1 on 2018-01-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180109_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
