# Generated by Django 2.0.1 on 2018-01-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_hours_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hours',
            old_name='username',
            new_name='account',
        ),
    ]
