# Generated by Django 2.0.1 on 2018-01-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180109_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='user',
        ),
    ]
