# Generated by Django 2.0.1 on 2018-01-10 19:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180110_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SqlLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SqlServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpu', models.IntegerField(default=4)),
                ('ram', models.IntegerField()),
                ('date_added', models.DateField(auto_now=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='myapp.OsVersion')),
            ],
        ),
        migrations.CreateModel(
            name='SqlVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sqlserver',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='myapp.SqlVersion'),
        ),
        migrations.AddField(
            model_name='sqllogs',
            name='servers',
            field=models.ManyToManyField(related_name='logs', to='myapp.SqlServer'),
        ),
    ]
