# Generated by Django 2.0.1 on 2018-01-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20180110_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
