# Generated by Django 2.0.1 on 2018-01-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_sqlserver_sap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlserver',
            name='mes',
            field=models.BooleanField(default=False),
        ),
    ]
