# Generated by Django 2.0.1 on 2018-01-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_sqlserver_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.SqlLog')),
                ('sqlserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.SqlServer')),
            ],
        ),
    ]
