# Generated by Django 2.0.1 on 2018-01-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_logserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqllog',
            name='servers',
        ),
        migrations.AddField(
            model_name='sqllog',
            name='servers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='myapp.SqlServer'),
            preserve_default=False,
        ),
    ]
