# Generated by Django 2.0.1 on 2018-01-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20180112_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logserver',
            name='log',
        ),
        migrations.RemoveField(
            model_name='logserver',
            name='sqlserver',
        ),
        migrations.DeleteModel(
            name='LogServer',
        ),
    ]
