# Generated by Django 2.0.1 on 2018-01-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_sqllog_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqllog',
            name='account',
            field=models.CharField(max_length=50),
        ),
    ]
