# Generated by Django 2.0.1 on 2018-01-17 22:28

from django.db import migrations


def init_landscape(apps, schema_editor):
    Landscape = apps.get_model("myapp", "Landscape")
    db_alias = schema_editor.connection.alias
    Landscape.objects.using(db_alias).bulk_create([
        Landscape(title="Development"),
        Landscape(title="Quality"),
        Landscape(title="Project Systems"),
        Landscape(title="Production"),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0022_landscape'),
    ]

    operations = [
        migrations.RunPython(init_landscape),
    ]
