# Generated by Django 2.0.1 on 2018-01-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_sqlserver_landscape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlserver',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
