# Generated by Django 2.0.1 on 2018-01-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20180118_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlserver',
            name='monitor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sqlserver',
            name='landscape',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.Landscape'),
        ),
    ]
