# Generated by Django 2.0.1 on 2018-01-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20180120_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlserver',
            name='port',
            field=models.IntegerField(default=1433),
        ),
    ]
