# Generated by Django 2.0.1 on 2018-01-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_sqlserver_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqllog',
            name='time_added',
            field=models.TimeField(auto_now=True),
        ),
    ]
