# Generated by Django 2.0.1 on 2018-01-21 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_sqllog_time_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlserver',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sqllog',
            name='time_added',
            field=models.TimeField(default=datetime.datetime(2018, 1, 21, 8, 36, 11, 596792)),
        ),
    ]
