# Generated by Django 2.1.7 on 2019-03-15 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20180121_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sqllog',
            name='time_added',
            field=models.TimeField(default=datetime.datetime(2019, 3, 15, 14, 37, 2, 924616)),
        ),
    ]
